### ISSUE TITLE
ActivityExplorerExport.ps1 Code Issue

### ISSUE THREAD

**Issue by KillerCloud-au** [ProfKaz/ActivityExplorerExport#1]
Hi @ProfKaz,

You have a very minor issue with your code, on line 279 you are missing a space between the $InitialPageSize and -OutputFormat....

current: $InitialPageSize-OutputFormat
fix: $InitialPageSize -OutputFormat

Screenshot below.

<img width="1107" alt="Screenshot 2024-07-31 at 11 12 53 AM" src="https://github.com/user-attachments/assets/0521da6f-db01-4ece-9985-9b8f3996f848">

**Comment by ProfKaz** [comment]
Thanks for the feedback, I fixed.
