### ISSUE TITLE
Incorrect workload name for Endpoints in ActivityExplorerWorkloadsSelector.json

### ISSUE THREAD

**Issue by skrilab** [ProfKaz/ActivityExplorerExport#2]
Hi! Not sure if we can call this an issue, but the provided naming for "Endpoint devices" in the 
 Script2.0/ConfigFiles/ActivityExplorerWorkloadsSelector.json config file is not correct. The correct string should be 'Endpoint'.
 
 If you run the 2.0 script with arguments that filter for Workloads (-WorkloadsFilter or -FilterOnlyByWorkloads) you get 0 results. If you change the "Endpoint devices" to "Endpoint" in the config file, the filters works.
 
Anyway thanks for creating this awsome script. Any future plans for implementing some automation, so this script could run unattended? :)

**Comment by ProfKaz** [comment]
Thanks for the feedback, I'll update soon the list, I found some bugs in the Microsoft side working in a new version, and that stop me to go forward, nevertheless, maybe a couple of months ago Microsoft update the documentation and they release the complete list of workloads.
